openapi: 3.0.0
info:
  description: |
    Image Scan Request/Result API
  version: "0.0.1"
  title: ImageScan
  contact:
    email: sunghyun_kim3@tmax.co.kr
tags:
  - name: Scan
paths:
  /apis/registry.tmax.io/v1/namespaces/{namespace}/scans/{name}:
    post:
      tags:
        - Request
      summary: Request image scan
      description: Request image scanning for specific registries/repositories/images. You can use '*' as a wildcard
      parameters:
        - in: "path"
          name: namespace
          description: namespace of image/repository/registry
          required: true
          schema:
            type: "string"
        - in: "path"
          name: name
          description: name to be used as ImageScanRequest resource name
          required: true
          schema:
            type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
            examples:
              multiRegistries:
                summary: Multiple Registries
                value:
                  registries:
                    - name: cicd-test
                      repositories:
                        - name: '*'
                    - name: cicd-test2
                      repositories:
                        - name: '*'
              multiRepositories:
                summary: Multiple Repositories
                value:
                  registries:
                    - name: cicd-test
                      repositories:
                        - name: 'cicd-test.test'
                          versions:
                            - "*"
                        - name: 'cicd-test.test2'
                          versions:
                            - "*"
              multiTags:
                summary: Multiple Tags
                value:
                  registries:
                    - name: cicd-test
                      repositories:
                        - name: 'cicd-test.test'
                          versions:
                            - "v1"
                            - "v2"
      responses:
        '201':
          description: Image scan requested
          content:
            application/json:
              schema:
                example:
                  imageScanRequestName: "{name}-<randomID>"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                example:
                  message: "error message"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                example:
                  message: "error message"
  /apis/registry.tmax.io/v1/namespaces/{namespace}/repositories/{name}/imagescanresults:
    get:
      tags:
        - Result
      summary: Get image scan results summary
      description: Get image scan results summary for whole repository (i.e. contains summary results for every tags in the repository)
      parameters:
        - in: "path"
          name: namespace
          description: namespace of repository
          required: true
          schema:
            type: "string"
        - in: "path"
          name: name
          description: name of repository
          required: true
          schema:
            type: "string"
      responses:
        '200':
          description: Image scan requested
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VulnerabilitySummary'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                example:
                  message: "error message"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                example:
                  message: "error message"
  /apis/registry.tmax.io/v1/namespaces/{namespace}/repositories/{name}/imagescanresults/{tag}:
    get:
      tags:
        - Result
      summary: Get image scan results
      description: Get image scan results for the specific tag
      parameters:
        - in: "path"
          name: namespace
          description: namespace of repository
          required: true
          schema:
            type: "string"
        - in: "path"
          name: name
          description: name of repository
          required: true
          schema:
            type: "string"
        - in: "path"
          name: tag
          description: tag of the image
          required: true
          schema:
            type: "string"
      responses:
        '200':
          description: Image scan requested
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VulnerabilityMap'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                example:
                  message: "error message"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                example:
                  message: "error message"
components:
  schemas:
    Request:
      type: object
      description: Scan request
      properties:
        registries:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              repositories:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    versions:
                      type: array
                      items:
                        type: string
    VulnerabilitySummary:
      type: object
      description: Summary of vulnerability results (the number of vulnerabilities with the specific severity)
      properties:
        Unknown:
          type: number
        Negligible:
          type: number
        Low:
          type: number
        Medium:
          type: number
        High:
          type: number
        Critical:
          type: number
    VulnerabilityMap:
      type: object
      description: Scan result map
      properties:
        Unknown:
          $ref: '#/components/schemas/Vulnerability'
        Negligible:
          $ref: '#/components/schemas/Vulnerability'
        Low:
          $ref: '#/components/schemas/Vulnerability'
        Medium:
          $ref: '#/components/schemas/Vulnerability'
        High:
          $ref: '#/components/schemas/Vulnerability'
        Critical:
          $ref: '#/components/schemas/Vulnerability'
    Vulnerability:
      type: object
      description: Scan result vulnerability
      properties:
        Name:
          type: string
        NamespacedName:
          type: string
        Description:
          type: string
        Link:
          type: string
        Severity:
          type: string
        FixedBy:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
